openapi: 3.0.0
info:
  title: auth
  version: '1.0'
  description: Handles user authetication and session tokens
  contact: {}
servers:
  - url: 'http://localhost:8070'
paths:
  '/getUID/{SessionToken}':
    parameters:
      - schema:
          type: string
        name: SessionToken
        in: path
        required: true
        description: User Session-Token from client device/browser
    get:
      summary: Get UID
      tags:
        - workout-app
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  IsValid:
                    type: boolean
                  UID:
                    type: string
                required:
                  - IsValid
              examples:
                example-success:
                  value:
                    IsValid: true
                    UID: testUID
                example-failure:
                  value:
                    IsValid: false
                    UID: ''
      operationId: get-UID
      description: Get the UID associated with a valid session token
  /apiVersion:
    get:
      summary: Get API Version
      tags:
        - workout-app
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  apiVersion:
                    type: number
                required:
                  - apiVersion
              examples: {}
      operationId: get-apiVersion
      description: Returns the symantec version number of the api
components:
  schemas: {}
tags:
  - name: workout-app
