openapi: 3.0.0
info:
  title: backend
  version: '1.0'
  description: Processes user data
  contact: {}
servers:
  - url: 'http://localhost:8090'
paths:
  '/userDaily/{week}/{day}/{UID}':
    parameters:
      - schema:
          type: string
        name: week
        in: path
        required: true
      - schema:
          type: string
        name: day
        in: path
        required: true
      - schema:
          type: string
        name: UID
        in: path
        required: true
    post:
      summary: ''
      operationId: post-generateUserBaseline
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  Fat:
                    type: integer
                  Carbs:
                    type: integer
                  Protein:
                    type: integer
                  TotalCalories:
                    type: integer
                  DayCalories:
                    type: integer
                  Weight:
                    type: integer
                  Cardio:
                    type: string
                  WeightTraining:
                    type: string
  '/userInfo/{UID}':
    parameters:
      - schema:
          type: string
        name: UID
        in: path
        required: true
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  FirstName:
                    type: string
                  LastName:
                    type: string
                  Weight:
                    type: integer
                  WaistCirc:
                    type: integer
                  HeightInches:
                    type: integer
                  LeanBodyMass:
                    type: integer
                  Age:
                    type: integer
                  Gender:
                    type: string
      description: ''
    post:
      summary: ''
      operationId: post-userInfo-UID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              examples:
                example-1:
                  value: {}
        '':
          content:
            application/json:
              schema:
                type: object
                properties:
                  FirstName:
                    type: string
                  LastName:
                    type: string
                  Weight:
                    type: integer
                  WaistCirc:
                    type: integer
                  HeightInches:
                    type: integer
                  LeanBodyMass:
                    type: integer
                  Age:
                    type: integer
                  Gender:
                    type: string
  '/userRecommendation/{week}/{UID}':
    parameters:
      - schema:
          type: number
        name: week
        in: path
        required: true
      - schema:
          type: string
        name: UID
        in: path
        required: true
    post:
      summary: ''
      operationId: post-userRecommendation-week-UID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  HighDayProtein:
                    type: integer
                  HighDayCarb:
                    type: integer
                  HighDayFat:
                    type: integer
                  HaighDayCalories:
                    type: integer
                  NormalDayProtein:
                    type: integer
                  NormalDayCarb:
                    type: integer
                  NormalDayFat:
                    type: integer
                  NormalDayCalories:
                    type: integer
                  LowDayProtein:
                    type: integer
                  LowDayFat:
                    type: integer
                  LowDayCalories:
                    type: integer
                  HIITCurrentCardioSession:
                    type: string
                  HIITChangeCardioSession:
                    type: string
                  HIIYCurrentCardioIntervals:
                    type: integer
                  HIITChangeCardioIntervals:
                    type: integer
                  Week:
                    type: integer
                  ModifiedDate:
                    type: string
  '/generateUserBaseline/{UID}':
    parameters:
      - schema:
          type: string
        name: UID
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-generateUserBaseline-UID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                FirstName:
                  type: string
                LastName:
                  type: string
                Weight:
                  type: integer
                WaistCirc:
                  type: integer
                HeightInches:
                  type: integer
                LeanBodyMass:
                  type: integer
                Age:
                  type: integer
                Gender:
                  type: string
components:
  schemas: {}
tags:
  - name: workout-app
