# Docker compose builds and runs multiple docker containers
# run simply with `docker-compose up`

version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 8090:8090
    environment:
      BACKEND_LISTEN_ADDRESS: 0.0.0.0:8090
    restart: on-failure

  auth:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    ports:
      - 8070:8070
    environment:
      AUTH_LISTEN_ADDRESS: 0.0.0.0:8070
    restart: on-failure

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 8080:8080
    environment:
      FRONTEND_WEBSITE_ADDRESS: localhost:8080
      FRONTEND_LISTEN_ADDRESS: 0.0.0.0:8080
      BACKEND_ADDRESS: host.docker.internal:8090
      AUTH_ADDRESS: host.docker.internal:8070
    restart: on-failure
