# Docker compose builds and runs multiple docker containers
# run simply with `docker-compose up`

version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 8090:8090
    environment:
      BACKEND_LISTEN_ADDRESS: 0.0.0.0:8090

  auth:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    ports:
      - 8070:8070
    environment:
      AUTH_LISTEN_ADDRESS: 0.0.0.0:8070

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 8080:8080
    links:
      - backend
      - auth
    environment:
      FRONTEND_WEBSITE_ADDRESS: localhost:8080
      FRONTEND_LISTEN_ADDRESS: 0.0.0.0:8080
      BACKEND_ADDRESS: backend:8090
      AUTH_ADDRESS: auth:8070
