---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-svc
  namespace: web
spec:
  selector:
    matchLabels:
      app: workoutsite
      svc: auth
  template:
    metadata:
      labels:
        app: workoutsite
        svc: auth
    spec:
     containers:
      - name: auth
        image: aduckonquack/workout-app-auth
        env:
          - name: AUTH_LISTEN_ADDRESS
            value: "0.0.0.0:8070"
          - name: REDIS_CONNECTION_STRING
            value: redis://redis:6379/0
          - name: PROVIDER_SECRET
            value: 02234a8a31839e192965c76bdbfb51ab01598cd8
          - name: PROVIDER_KEY
            value: 706d61cb56c4064426bb
          - name: WEBSITE_BASE_URL
            value: "https://dreamandachieve.net"
        imagePullPolicy: Always
        ports:
        - name: auth-port
          containerPort: 8070
        resources:
          limits:
            cpu: "1000m"
            memory: "600Mi"
          requests:
            cpu: "400m"
            memory: "200Mi"

---

apiVersion: v1
kind: Service
metadata:
  namespace: web
  name: auth
spec:
  ports:
  - name: auth
    port: 8070
    protocol: TCP
  selector:
    svc: auth
