---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web-svc
  namespace: web
spec:
  selector:
    matchLabels:
      app: workoutsite
      svc: frontend-web
  template:
    metadata:
      labels:
        app: workoutsite
        svc: frontend-web
    spec:
     containers:
      - name: frontend-web
        image: 35.236.22.57:5000/frontend-web
        env:
          - name: FRONTEND_LISTEN_ADDRESS
            value: 0.0.0.0:80
          - name: FRONTEND_WEBSITE_URL
            value: workout-site.com
        imagePullPolicy: IfNotPresent
        ports:
        - name: web-port
          containerPort: 80
        resources:
          limits:
            cpu: "1000m"
            memory: "600Mi"
          requests:
            cpu: "400m"
            memory: "200Mi"

---
apiVersion: v1
kind: Service
metadata:
  namespace: web
  name: frontend-web
spec:
  ports:
  - name: frontend-web
    port: 80
    protocol: TCP
  selector:
    svc: frontend-web

---

apiVersion: v1
kind: Service
metadata:
  name: frontweb-out
  namespace: web
spec:
  selector:
      svc: frontend-web
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-web-ingress
  annotations:
    app.kubernetes.io/name: ingress-nginx
spec:
  rules:
    - host: "dreamandachieve.net"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: frontend-web
                port:
                  number: 80