---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
  namespace: web
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: qahanna2@gmail.com
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-key
    solvers:
    - http01:
       ingress:
         class: nginx

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: workout-app
  namespace: web
spec:
  dnsNames:
    - dreamandachieve.net
  secretName: workout-app-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer