name: integration-tests

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
  pull_request:
    branches: [ master ]

jobs:
  ### build service images
  build-auth:
    runs-on: [self-hosted, docker]
    steps:
    - uses: actions/checkout@v2
    - run: docker build -t auth:$(git rev-parse --short HEAD) -f ./auth/Dockerfile .
  build-database:
    runs-on: [self-hosted, docker]
    steps:
    - uses: actions/checkout@v2
    - run: docker build -t database:$(git rev-parse --short HEAD) -f ./database/Dockerfile .

  ### build test images
  build-auth-test:
    needs: build-auth
    runs-on: [self-hosted, docker]
    steps:
    - uses: actions/checkout@v2
    - run: docker build -t auth-test:$(git rev-parse --short HEAD) -f ./auth/tests.Dockerfile .
  build-database-test:
    needs: build-database
    runs-on: [self-hosted, docker]
    steps:
    - uses: actions/checkout@v2
    - run: docker build -t database-test:$(git rev-parse --short HEAD) -f ./database/tests.Dockerfile .
  build-mongodb-mock:
    runs-on: [self-hosted, docker]
    steps:
    - uses: actions/checkout@v2
    - run: docker build -t mongodb-mock-database:$(git rev-parse --short HEAD) -f ./database/mongoDB/Dockerfile .

  ### run tests against service images
  test-database:
    needs: [build-mongodb-mock, build-database-test]
    runs-on: [self-hosted, docker]
    steps:
    - uses: actions/checkout@v2
    - run: docker stop mongodb-mock-database || :;
    - run: docker stop database-service || :;
    - run: docker run --rm -d --name=mongodb-mock-database -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME=adminz -e MONGO_INITDB_ROOT_PASSWORD=cheeksbutt mongodb-mock-database:$(git rev-parse --short HEAD)
    - run: sleep 2 && docker run --rm -d --name=database-service -p 8050:8050 --net=host database:$(git rev-parse --short HEAD)
    - run: sleep 5 && docker run --rm -i --name=database-test --net=host database-test:$(git rev-parse --short HEAD)
    - run: docker stop mongodb-mock-database
    - run: docker stop database-service
  test-auth:
    needs: build-auth-test
    runs-on: [self-hosted, docker]
    steps:
    - uses: actions/checkout@v2
    - run: docker stop auth-service || :;
    - run: docker run -d --name=auth-service -p 8070:8070 --rm -e AUTH_LISTEN_ADDRESS="0.0.0.0:8070" -e AUTH_FIREBASE_CREDENTIALS='{test}' auth:$(git rev-parse --short HEAD)
    - run: sleep 5 && docker run --rm -i --name=auth-test --net=host auth-test:$(git rev-parse --short HEAD)
    - run: docker stop auth-service
